version: '4.0'
services:
  wp_web_server:
    container_name: 'wp_web_server'
    build:
      args:
        user: long
        uid: 1000
      context: ./source/
      dockerfile: ../dockerfile
    environment:
      PHP_IDE_CONFIG: "serverName=web_server"
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    image: wp-app
    restart: unless-stopped
    volumes:
      - ./source:/var/www/html
    working_dir: /var/www/html
    networks:
      - app-wp-network
  app_nginx_server:
    container_name: 'app_nginx_server'
    image: nginx:stable-alpine
    restart: unless-stopped
    ports:
      - '${WEB_PORT}:81'
    volumes:
      - ./source:/var/www/html
      - ./nginx/conf.d:/etc/nginx/conf.d/
      - ./nginx/logs:/var/log/nginx/
    networks:
      - app-wp-network
  db_server:
    container_name: 'wp_db_server'
    image: mariadb:10.5
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: Admin123
      MARIADB_DATABASE: wp_db
      MARIADB_USER: admin
      MARIADB_PASSWORD: Admin123
    ports:
      - "${MYSQL_PORT}:3306"
    #volumes:
      #- ./db/init.sql:/docker-entrypoint-initdb.d/${DB_SOURCE}
      #- ./db/entrypoint.sh:/docker-entrypoint-initdb.d/${DB_CMD}
    networks:
      - app-wp-network
#Docker Networks
networks:
  app-wp-network:
    driver: bridge
