<link rel="icon" type="image/png" href="<?php echo getPublicFile('theme/images/icons/favicon.png'); ?>"/>
<link rel="stylesheet" type="text/css" href="<?php echo getPublicFile('theme/vendor/bootstrap/css/bootstrap.min.css'); ?>">
<link rel="stylesheet" type="text/css" href="<?php echo getPublicFile('theme/fonts/font-awesome-4.7.0/css/font-awesome.min.css'); ?>">
<link rel="stylesheet" type="text/css" href="<?php echo getPublicFile('theme/fonts/iconic/css/material-design-iconic-font.min.css'); ?>">
<link rel="stylesheet" type="text/css" href="<?php echo getPublicFile('theme/fonts/linearicons-v1.0.0/icon-font.min.css'); ?>">
<link rel="stylesheet" type="text/css" href="<?php echo getPublicFile('theme/vendor/animate/animate.css'); ?>">
<link rel="stylesheet" type="text/css" href="<?php echo getPublicFile('theme/vendor/css-hamburgers/hamburgers.min.css'); ?>">
<link rel="stylesheet" type="text/css" href="<?php echo getPublicFile('theme/vendor/animsition/css/animsition.min.css'); ?>">
<link rel="stylesheet" type="text/css" href="<?php echo getPublicFile('theme/vendor/select2/select2.min.css'); ?>">
<link rel="stylesheet" type="text/css" href="<?php echo getPublicFile('theme/vendor/daterangepicker/daterangepicker.css'); ?>">
<link rel="stylesheet" type="text/css" href="<?php echo getPublicFile('theme/vendor/slick/slick.css'); ?>">
<link rel="stylesheet" type="text/css" href="<?php echo getPublicFile('theme/vendor/MagnificPopup/magnific-popup.css'); ?>">
<link rel="stylesheet" type="text/css" href="<?php echo getPublicFile('theme/vendor/perfect-scrollbar/perfect-scrollbar.css'); ?>">
<link rel="stylesheet" type="text/css" href="<?php echo getPublicFile('theme/css/util.css'); ?>">
<link rel="stylesheet" type="text/css" href="<?php echo getPublicFile('theme/css/main.css'); ?>">